"""group id

Revision ID: 0a13da517bb9
Revises: a4b569647191
Create Date: 2026-03-11 06:19:56.646940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a13da517bb9'
down_revision: Union[str, Sequence[str], None] = 'a4b569647191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'guestPresence', ['id'])
    op.create_unique_constraint(None, 'guests', ['id'])
    op.create_unique_constraint(None, 'invites', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_constraint(None, 'guestPresence', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    # ### end Alembic commands ###
