"""add relationship update table invite

Revision ID: 23f36f42f875
Revises: 5029523216f1
Create Date: 2026-03-12 05:41:12.024899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f36f42f875'
down_revision: Union[str, Sequence[str], None] = '5029523216f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('type', sa.String(length=25), nullable=True))
    op.create_unique_constraint(None, 'invites', ['event_id', 'ticket_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_column('invites', 'type')
    # ### end Alembic commands ###
