"""add group_id to uuserss

Revision ID: 285582f36dc7
Revises: 8091172e5952
Create Date: 2026-03-07 21:40:19.612929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285582f36dc7'
down_revision: Union[str, Sequence[str], None] = '8091172e5952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'guestPresence', ['id'])
    op.create_unique_constraint(None, 'guests', ['id'])
    op.create_unique_constraint(None, 'invites', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_constraint(None, 'guestPresence', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    # ### end Alembic commands ###
