"""update table"

Revision ID: 3c454dc6795d
Revises: a46155690096
Create Date: 2026-03-04 14:05:15.117840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c454dc6795d'
down_revision: Union[str, Sequence[str], None] = 'a46155690096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
