"""migration 001/3

Revision ID: 3cf5b65abe0a
Revises: ad4fc3e44d88
Create Date: 2026-09-28 07:23:13.458918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf5b65abe0a'
down_revision: Union[str, Sequence[str], None] = 'ad4fc3e44d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_email_event'), 'guests', type_='unique')
    op.drop_constraint(op.f('uix_telephone_event'), 'guests', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_telephone_event'), 'guests', ['telephone', 'event_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uix_email_event'), 'guests', ['email', 'event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
