"""add relationship to event and invite update

Revision ID: 5029523216f1
Revises: 3da2ee020aa2
Create Date: 2026-03-12 05:23:23.444948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5029523216f1'
down_revision: Union[str, Sequence[str], None] = '3da2ee020aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invites', ['ticket_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    # ### end Alembic commands ###
