"""update event and groups table

Revision ID: 5387aafe4b9f
Revises: 7e0da54a6440
Create Date: 2026-03-07 11:27:05.159519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5387aafe4b9f'
down_revision: Union[str, Sequence[str], None] = '7e0da54a6440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'guestPresence', ['id'])
    op.create_unique_constraint(None, 'guests', ['id'])
    op.create_unique_constraint(None, 'invites', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_constraint(None, 'guestPresence', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    # ### end Alembic commands ###
