"""update user table

Revision ID: 5aed06669ffe
Revises: 3c454dc6795d
Create Date: 2026-03-05 11:34:33.660691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aed06669ffe'
down_revision: Union[str, Sequence[str], None] = '3c454dc6795d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
