"""update event again

Revision ID: 5c5965cdbf9f
Revises: d8c4bfa75f0b
Create Date: 2026-03-05 20:20:55.927672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5965cdbf9f'
down_revision: Union[str, Sequence[str], None] = 'd8c4bfa75f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('couple_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'couple_name')
    # ### end Alembic commands ###
