"""init migrations

Revision ID: 5d11ccef5e2c
Revises: 
Create Date: 2026-02-20 10:14:33.480213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d11ccef5e2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('guests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('guest_type', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'event_id', name='uix_email_event'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('qr_token'),
    sa.UniqueConstraint('telephone', 'event_id', name='uix_telephone_event')
    )
    op.create_table('invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guest_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('qr_token', sa.Uuid(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('guestPresence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guest_id', sa.String(), nullable=False),
    sa.Column('invite_id', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guestPresence')
    op.drop_table('invites')
    op.drop_table('guests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
