"""initial migrations

Revision ID: 6f08a1b03127
Revises: 
Create Date: 2026-06-12 16:27:51.766712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f08a1b03127'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('buyer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('buyer_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticket_type', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('ticket_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('devise', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_pdf_ready', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('downloaded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('orders_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['external_users.id'], name=op.f('orders_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_event_id'), 'orders', ['event_id'], unique=False)
    op.create_index(op.f('ix_orders_buyer_number'), 'orders', ['buyer_number'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('group_roles',
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('group_roles_group_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('group_roles_role_id_fkey')),
    sa.PrimaryKeyConstraint('group_id', 'role_id', name=op.f('group_roles_pkey'))
    )
    op.create_table('groups',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('groups_pkey')),
    sa.UniqueConstraint('name', name=op.f('groups_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('external_users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('external_users_pkey'))
    )
    op.create_index(op.f('ix_external_users_phone_number'), 'external_users', ['phone_number'], unique=True)
    op.create_table('otps',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ext_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ext_user_id'], ['external_users.id'], name=op.f('otps_ext_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('otps_pkey'))
    )
    op.create_table('user_groups',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('user_groups_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_groups_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('user_groups_pkey'))
    )
    op.create_table('guests',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('guest_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('qr_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('get_pass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('photo_public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('guests_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('guests_pkey')),
    sa.UniqueConstraint('email', 'event_id', name=op.f('uix_email_event'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('telephone', 'event_id', name=op.f('uix_telephone_event'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_guests_qr_token'), 'guests', ['qr_token'], unique=True)
    op.create_index(op.f('ix_guests_get_pass'), 'guests', ['get_pass'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_pkey')),
    sa.UniqueConstraint('name', name=op.f('permissions_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tickets',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('seri', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('participator_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('participator_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('qr_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('get_pass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('totp_secret', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('is_scanned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('tickets_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('tickets_order_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_pkey'))
    )
    op.create_index(op.f('ix_tickets_qr_token'), 'tickets', ['qr_token'], unique=True)
    op.create_index(op.f('ix_tickets_participator_number'), 'tickets', ['participator_number'], unique=False)
    op.create_index(op.f('ix_tickets_order_id'), 'tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_get_pass'), 'tickets', ['get_pass'], unique=False)
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guest_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qr_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('invites_guest_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invites_pkey'))
    )
    op.create_index(op.f('ix_invites_qr_token'), 'invites', ['qr_token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_roles_pkey'))
    )
    op.create_table('ticket_prices',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ticket_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('ticket_prices_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_prices_pkey'))
    )
    op.create_index(op.f('ix_ticket_prices_id'), 'ticket_prices', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('name', name=op.f('roles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('guestPresence',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guest_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('invite_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('send_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('guestPresence_guest_id_fkey')),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], name=op.f('guestPresence_invite_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('guestPresence_pkey'))
    )
    op.create_index(op.f('ix_guestPresence_guest_id'), 'guestPresence', ['guest_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('couple_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('couple_phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('guest_present', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('greeting_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('photo_public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sold_seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('events_created_by_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('events_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    # ### end Alembic commands ###
