"""add relationship update table invite 00 add deleted unique

Revision ID: 8cf397e1fc30
Revises: bc8fff6ac60d
Create Date: 2026-03-12 05:59:59.007326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf397e1fc30'
down_revision: Union[str, Sequence[str], None] = 'bc8fff6ac60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invites_ticket_number_key'), 'invites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('invites_ticket_number_key'), 'invites', ['ticket_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
