"""add html5qrcode

Revision ID: a06c4be9cb12
Revises: 5d11ccef5e2c
Create Date: 2026-02-21 11:06:44.585542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06c4be9cb12'
down_revision: Union[str, Sequence[str], None] = '5d11ccef5e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'guestPresence', ['id'])
    op.create_unique_constraint(None, 'guests', ['id'])
    op.create_unique_constraint(None, 'invites', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_constraint(None, 'guestPresence', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    # ### end Alembic commands ###
