"""add group_id to uuserss 00

Revision ID: a4b569647191
Revises: 285582f36dc7
Create Date: 2026-03-07 21:59:32.646858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b569647191'
down_revision: Union[str, Sequence[str], None] = '285582f36dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_group_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_group_id_fkey'), 'users', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
