"""migration 001/2

Revision ID: ad4fc3e44d88
Revises: be039a4ba78d
Create Date: 2026-09-27 15:48:43.911664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4fc3e44d88'
down_revision: Union[str, Sequence[str], None] = 'be039a4ba78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_pictures_id'), table_name='event_pictures')
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'guestPresence', ['id'])
    op.drop_constraint(op.f('uix_email_event'), 'guests', type_='unique')
    op.drop_constraint(op.f('uix_telephone_event'), 'guests', type_='unique')
    op.create_unique_constraint(None, 'guests', ['id'])
    op.create_unique_constraint(None, 'invites', ['id'])
    op.create_unique_constraint(None, 'programs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programs', type_='unique')
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_constraint(None, 'guests', type_='unique')
    op.create_unique_constraint(op.f('uix_telephone_event'), 'guests', ['telephone', 'event_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uix_email_event'), 'guests', ['email', 'event_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'guestPresence', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    op.create_index(op.f('ix_event_pictures_id'), 'event_pictures', ['id'], unique=False)
    # ### end Alembic commands ###
