"""add relationship update table invite 00

Revision ID: bc8fff6ac60d
Revises: 2930cd231499
Create Date: 2026-03-12 05:55:38.908661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8fff6ac60d'
down_revision: Union[str, Sequence[str], None] = '2930cd231499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invites_event_id_ticket_number_key'), 'invites', type_='unique')
    op.create_unique_constraint('unique event ticket number', 'invites', ['event_id', 'ticket_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique event ticket number', 'invites', type_='unique')
    op.create_unique_constraint(op.f('invites_event_id_ticket_number_key'), 'invites', ['event_id', 'ticket_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
