"""update change group to group_id

Revision ID: c905cdda98b4
Revises: 5c5965cdbf9f
Create Date: 2026-03-05 21:08:04.413416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c905cdda98b4'
down_revision: Union[str, Sequence[str], None] = '5c5965cdbf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_group_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'groups', ['group_id'], ['id'])
    op.drop_column('users', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_group_fkey'), 'users', 'groups', ['group'], ['id'])
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###
