"""update event

Revision ID: d8c4bfa75f0b
Revises: 5aed06669ffe
Create Date: 2026-03-05 19:00:41.591064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c4bfa75f0b'
down_revision: Union[str, Sequence[str], None] = '5aed06669ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('created_by', sa.String(), nullable=True))
    op.alter_column('events', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'events', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
