"""add attribut

Revision ID: e0a920a8c33d
Revises: 8eb53bdc5e03
Create Date: 2026-03-12 04:34:38.504450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a920a8c33d'
down_revision: Union[str, Sequence[str], None] = '8eb53bdc5e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('serie', sa.String(), nullable=True))
    op.add_column('events', sa.Column('programme', sa.Text(), nullable=True))
    op.add_column('invites', sa.Column('ticket_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'ticket_number')
    op.drop_column('events', 'programme')
    op.drop_column('events', 'serie')
    # ### end Alembic commands ###
