"""update event and groups table once again

Revision ID: ee79d6bc20ce
Revises: 5387aafe4b9f
Create Date: 2026-03-07 11:44:51.373452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee79d6bc20ce'
down_revision: Union[str, Sequence[str], None] = '5387aafe4b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('group_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'events', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'group_id')
    # ### end Alembic commands ###
