"""migration 001

Revision ID: f81ce12b3af3
Revises: a23b870616b1
Create Date: 2026-09-17 12:38:12.349305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81ce12b3af3'
down_revision: Union[str, Sequence[str], None] = 'a23b870616b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_pictures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'guestPresence', ['id'])
    op.create_unique_constraint(None, 'guests', ['id'])
    op.create_unique_constraint(None, 'invites', ['id'])
    op.create_unique_constraint(None, 'programs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programs', type_='unique')
    op.drop_constraint(None, 'invites', type_='unique')
    op.drop_constraint(None, 'guests', type_='unique')
    op.drop_constraint(None, 'guestPresence', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_table('event_pictures')
    # ### end Alembic commands ###
