"""add guest_present

Revision ID: fb94a76ee38a
Revises: 0a13da517bb9
Create Date: 2026-03-11 15:13:04.691688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb94a76ee38a'
down_revision: Union[str, Sequence[str], None] = '0a13da517bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('guest_present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'guest_present')
    # ### end Alembic commands ###
